[package]
name = "zabr"
version = "0.1.0"
authors = ["Akshat Mahajan <akshatm.bkk@gmail.com>"]
edition = "2018"

[dependencies]
crossbeam = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
